version: "3.8"
services:
  app:
    build: .
    container_name: lead-scoring-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/lead_scoring
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
